package com.zhangchangq.project.dao;

import com.zhangchangq.project.dataobject.SequenceDo;

public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    int insert(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    int insertSelective(SequenceDo record);


    SequenceDo getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    SequenceDo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequnce_info
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    int updateByPrimaryKey(SequenceDo record);
}