package com.zhangchangq.project.dataobject;

public class SequenceDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequnce_info.name
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequnce_info.current_value
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequnce_info.step
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequnce_info.name
     *
     * @return the value of sequnce_info.name
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequnce_info.name
     *
     * @param name the value for sequnce_info.name
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequnce_info.current_value
     *
     * @return the value of sequnce_info.current_value
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequnce_info.current_value
     *
     * @param currentValue the value for sequnce_info.current_value
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequnce_info.step
     *
     * @return the value of sequnce_info.step
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequnce_info.step
     *
     * @param step the value for sequnce_info.step
     *
     * @mbg.generated Wed Mar 27 10:57:49 CST 2019
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}